from __future__ import annotations

# Console
CONSOLE_VIEW = "CONSOLE_VIEW"
CONSOLE_SEND = "CONSOLE_SEND"

# Server
SERVER_VIEW = "SERVER_VIEW"
SERVER_MANAGE = "SERVER_MANAGE"

# Players
PLAYERS_VIEW = "PLAYERS_VIEW"
PLAYERS_KICK = "PLAYERS_KICK"
PLAYERS_BAN = "PLAYERS_BAN"
PLAYERS_OP = "PLAYERS_OP"

# Properties
PROPERTIES_VIEW = "PROPERTIES_VIEW"
PROPERTIES_EDIT = "PROPERTIES_EDIT"

# Addons
ADDONS_VIEW = "ADDONS_VIEW"
ADDONS_MANAGE = "ADDONS_MANAGE"

# Backups
BACKUPS_VIEW = "BACKUPS_VIEW"
BACKUPS_CREATE = "BACKUPS_CREATE"
BACKUPS_RESTORE = "BACKUPS_RESTORE"
BACKUPS_DELETE = "BACKUPS_DELETE"

# Users
USERS_VIEW = "USERS_VIEW"
USERS_CREATE = "USERS_CREATE"
USERS_EDIT = "USERS_EDIT"
USERS_DELETE = "USERS_DELETE"

# Files
FILES_VIEW = "FILES_VIEW"
FILES_EDIT = "FILES_EDIT"

# Audit
AUDIT_VIEW = "AUDIT_VIEW"

# Settings
SETTINGS_VIEW = "SETTINGS_VIEW"
SETTINGS_EDIT = "SETTINGS_EDIT"

ALL_PERMISSIONS = [
    CONSOLE_VIEW, CONSOLE_SEND,
    SERVER_VIEW, SERVER_MANAGE,
    PLAYERS_VIEW, PLAYERS_KICK, PLAYERS_BAN, PLAYERS_OP,
    PROPERTIES_VIEW, PROPERTIES_EDIT,
    ADDONS_VIEW, ADDONS_MANAGE,
    BACKUPS_VIEW, BACKUPS_CREATE, BACKUPS_RESTORE, BACKUPS_DELETE,
    USERS_VIEW, USERS_CREATE, USERS_EDIT, USERS_DELETE,
    FILES_VIEW, FILES_EDIT,
    AUDIT_VIEW,
    SETTINGS_VIEW, SETTINGS_EDIT,
]
